const listingsData = [
  {
    name: "nina-sky",
    address: "550 General Schmitty street",
    city: "Montreal",
    province: "QC",
    rooms: 3,
    price: 320000,
    floorSpace: 2000,
    extras: ["elevator", "gym"],
    homeType: "House",
    img: "https://tobiarchitects.com/wp-content/uploads/2017/11/1.1-min.jpg",
    date: "02/04/2019"
  },
  {
    name: "nina-sky",
    address: "3276 Water Street",
    city: "Kitchener",
    province: "ON",
    rooms: 2,
    price: 220000,
    floorSpace: 2500,
    extras: ["elevator", "gym"],
    homeType: "Multi Home",
    img: "https://tobiarchitects.com/wp-content/uploads/2017/11/1.1-min.jpg",
    date: "02/04/2019"
  },
  {
    name: "nina-sky",
    address: "211 Rue Montcalm",
    city: "Montreal",
    province: "QC",
    rooms: 1,
    price: 620000,
    floorSpace: 1500,
    extras: ["elevator", "gym"],
    homeType: "Condo",
    img: "https://tobiarchitects.com/wp-content/uploads/2017/11/1.1-min.jpg",
    date: "02/04/2019"
  },
  {
    name: "nina-sky",
    address: "263 Zim Road",
    city: "Ottawa",
    province: "ON",
    rooms: 1,
    price: 320000,
    floorSpace: 1000,
    extras: ["elevator", "gym"],
    homeType: "Apartment",
    img: "https://tobiarchitects.com/wp-content/uploads/2017/11/1.1-min.jpg",
    date: "02/04/2019"
  },
  {
    name: "nina-sky",
    address: "1931  Nelson Street",
    city: "Oshawa",
    province: "ON",
    rooms: 0,
    price: 420000,
    floorSpace: 500,
    extras: ["elevator", "gym"],
    homeType: "Studio",
    img: "https://tobiarchitects.com/wp-content/uploads/2017/11/1.1-min.jpg",
    date: "02/04/2019"
  },
  {
    name: "nina-sky",
    address: "1200 Crystl Ship avenue",
    city: "Mississauga",
    province: "ON",
    rooms: 2,
    price: 150000,
    floorSpace: 800,
    extras: ["elevator", "gym"],
    homeType: "Condo",
    img: "https://tobiarchitects.com/wp-content/uploads/2017/11/1.1-min.jpg",
    date: "02/04/2019"
  },
  {
    name: "nina-sky",
    address: "700 Phasma Chrome drive",
    city: "Montreal",
    province: "QC",
    rooms: 1,
    price: 290000,
    floorSpace: 900,
    extras: ["elevator", "gym"],
    homeType: "Room",
    img: "https://tobiarchitects.com/wp-content/uploads/2017/11/1.1-min.jpg",
    date: "02/04/2019"
  },
  {
    name: "nina-sky",
    address: "460 Aurora dust view",
    city: "Montreal",
    province: "QC",
    rooms: 2,
    price: 690000,
    floorSpace: 900,
    extras: ["elevator", "gym"],
    homeType: "Loft",
    img: "https://tobiarchitects.com/wp-content/uploads/2017/11/1.1-min.jpg",
    date: "02/04/2019"
  },
  {
    name: "nina-sky",
    address: "200 Press crescent",
    city: "Montreal",
    province: "QC",
    rooms: 3,
    price: 320000,
    floorSpace: 2000,
    extras: ["finished_basement"],
    homeType: "House",
    img: "https://tobiarchitects.com/wp-content/uploads/2017/11/1.1-min.jpg",
    date: "02/04/2019"
  },
  {
    name: "nina-sky",
    address: "678 Palace way",
    city: "Toronto",
    province: "ON",
    rooms: 2,
    price: 220000,
    floorSpace: 2500,
    extras: ["finished_basement"],
    homeType: "Multi Home",
    img: "https://tobiarchitects.com/wp-content/uploads/2017/11/1.1-min.jpg",
    date: "02/04/2019"
  },
  {
    name: "nina-sky",
    address: "341 Crimson star drive",
    city: "Montreal",
    province: "QC",
    rooms: 2,
    price: 620000,
    floorSpace: 1500,
    extras: ["elevator", "gym"],
    homeType: "Condo",
    img: "https://tobiarchitects.com/wp-content/uploads/2017/11/1.1-min.jpg",
    date: "02/04/2019"
  },
  {
    name: "nina-sky",
    address: "201 Crystal Wall road",
    city: "Ottawa",
    province: "ON",
    rooms: 1,
    price: 320000,
    floorSpace: 1000,
    extras: ["elevator", "swimming_pool"],
    homeType: "Apartment",
    img: "https://tobiarchitects.com/wp-content/uploads/2017/11/1.1-min.jpg",
    date: "02/04/2019"
  },
  {
    name: "nina-sky",
    address: "4444 Jay way",
    city: "Vancouver",
    province: "BC",
    rooms: 0,
    price: 120000,
    floorSpace: 500,
    extras: ["elevator", "gym"],
    homeType: "Studio",
    img: "https://tobiarchitects.com/wp-content/uploads/2017/11/1.1-min.jpg",
    date: "02/04/2019"
  },
  {
    name: "nina-sky",
    address: "206 Metal Feelings way",
    city: "Mississauga",
    province: "ON",
    rooms: 2,
    price: 380000,
    floorSpace: 800,
    extras: ["elevator", "gym", "swimming_pool"],
    homeType: "Condo",
    img: "https://tobiarchitects.com/wp-content/uploads/2017/11/1.1-min.jpg",
    date: "02/04/2019"
  },
  {
    name: "nina-sky",
    address: "111 Rue Noveau Croissant",
    city: "Montreal",
    province: "QC",
    rooms: 1,
    price: 190000,
    floorSpace: 900,
    extras: ["elevator"],
    homeType: "Studio",
    img: "https://tobiarchitects.com/wp-content/uploads/2017/11/1.1-min.jpg",
    date: "02/04/2019"
  },
  {
    name: "nina-sky",
    address: "1200 Stardust Road",
    city: "Toronto",
    province: "ON",
    rooms: 2,
    price: 680000,
    floorSpace: 900,
    extras: ["elevator", "finished_basement"],
    homeType: "Loft",
    img: "https://tobiarchitects.com/wp-content/uploads/2017/11/1.1-min.jpg",
    date: "02/04/2019"
  }
];

export default listingsData;
